number:
  greater_than: 0
  less_than: 10
user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
page:
  paginate: 12
image:
  size: 5
  format: ["image/jpeg", "image/gif", "image/png"]
